### ISSUE TITLE
Download Link 404s

### ISSUE THREAD

**Issue by Helw150** [google-research/xtreme-up#1]
Hi xtreme-up team! Thanks for the great work. I'm excited to evaluate on some of the newly released datasets in the benchmark!

However, the dataset download link in the repo (https://storage.googleapis.com/xtreme-up/v1.0/xtreme-up.jsonl.tgz) currently leads to a dead end.

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: xtreme-up/v1.0/xtreme-up.jsonl.tgz</Details>
</Error>
```

Let me know if I can provide any other details to help diagnose the issue.

Cheers,
Will Held

**Comment by jhclark-google** [comment]
Sorry about that, Will. I'm looking into it now (also seems I didn't have email notifications for new issues enabled yet).

**Comment by jhclark-google** [comment]
Okay, I botched the path when I bumped the version to v1.1. Please find the current version at https://storage.googleapis.com/xtreme-up/xtreme-up-v1.1.jsonl.tgz.

This will be reflected on the README.md shortly.

**Comment by Helw150** [comment]
Thanks!
